version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "4000:4000"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    command: >
      sh -c "npm install prisma @prisma/client --legacy-peer-deps && 
             npx prisma generate --schema ./prisma/schema.prisma && 
             npx prisma migrate deploy --schema ./prisma/schema.prisma && 
             node dist/main.js"
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "5173:5173"
    env_file:
      - .env

volumes:
  db_data: