import {
  faWineGlass,
  faStar,
  faGear,
  faMusic,
  faFilm,
  faPalette,
  faRobot,
  faCakeCandles,
  faTree,
  faDollarSign,
  faThumbsUp,
  faEyeLowVision,
  faBacteria,
  faDog,
  faFan,
  faMasksTheater,
  faPoo,
  faBriefcase,
  faPersonRunning,
  faCarrot,
  faPizzaSlice,
  faMugHot,
  faGamepad,
  faCampground,
  faFrog,
  faPersonHiking,
  faPaw,
  faCat,
  faCrow,
  faGift,
  faSun,
  faCode,
  faFire,
} from '@fortawesome/free-solid-svg-icons';
import { faTiktok, faGithub, faFortAwesome } from '@fortawesome/free-brands-svg-icons';
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core';

export const ICON_PATTERN_IDS = [
  'wine',
  'star',
  'gear',
  'music',
  'film',
  'palette',
  'robot',
  'cake',
  'tree',
  'dollar',
  'thumbs-up',
  'low-vision',
  'bacteria',
  'dog',
  'fan',
  'fort',
  'github',
  'theatre',
  'poo',
  'tiktok',
  'business',
  'sport',
  'carrot',
  'pizza',
  'coffee',
  'game',
  'camp',
  'frog',
  'hiking',
  'paw',
  'cat',
  'bird',
  'gift',
  'sun',
  'code',
  'fire',
] as const;

export type IconPatternId = (typeof ICON_PATTERN_IDS)[number];

export type IconPatternMeta = {
  label: string;
  icon: IconDefinition;
  tagHint: string;
};

export const ICON_PATTERN_META: Record<IconPatternId, IconPatternMeta> = {
  wine:     { label: 'Wine Night',   icon: faWineGlass,     tagHint: 'Food' },
  star:     { label: 'Star Power',   icon: faStar,          tagHint: 'Other' },
  gear:     { label: 'Tech Gear',    icon: faGear,          tagHint: 'Tech' },
  music:    { label: 'Music Beat',   icon: faMusic,         tagHint: 'Music' },
  film:     { label: 'Movie Night',  icon: faFilm,          tagHint: 'Other' },
  palette:  { label: 'Art Studio',   icon: faPalette,       tagHint: 'Other' },
  robot:    { label: 'Robot Mode',   icon: faRobot,         tagHint: 'Tech' },
  cake:     { label: 'Birthday Bash', icon: faCakeCandles,  tagHint: 'Food' },
  tree:     { label: 'Nature Trip',  icon: faTree,          tagHint: 'Other' },
  dollar:   { label: 'Money Talks',  icon: faDollarSign,    tagHint: 'Business' },
  'thumbs-up': { label: 'Good Vibes', icon: faThumbsUp,     tagHint: 'Other' },
  'low-vision': { label: 'Low Vision', icon: faEyeLowVision, tagHint: 'Other' },
  bacteria: { label: 'Bacteria Lab', icon: faBacteria,      tagHint: 'Tech' },
  dog:      { label: 'Dog Days',     icon: faDog,           tagHint: 'Other' },
  fan:      { label: 'Cool Breeze',  icon: faFan,           tagHint: 'Other' },
  fort:     { label: 'Fort Zone',    icon: faFortAwesome,   tagHint: 'Other' },
  github:   { label: 'GitHub Hub',   icon: faGithub,        tagHint: 'Tech' },
  theatre:  { label: 'Theatre Night', icon: faMasksTheater, tagHint: 'Other' },
  poo:      { label: 'Poo Mood',     icon: faPoo,           tagHint: 'Other' },
  tiktok:   { label: 'TikTok Vibe', icon: faTiktok,        tagHint: 'Other' },
  business: { label: 'Business',     icon: faBriefcase,     tagHint: 'Business' },
  sport:    { label: 'Sport Energy', icon: faPersonRunning, tagHint: 'Sport' },
  carrot:   { label: 'Veggie Vibes', icon: faCarrot,        tagHint: 'Food' },
  pizza:    { label: 'Pizza Party',  icon: faPizzaSlice,    tagHint: 'Food' },
  coffee:   { label: 'Coffee Time',  icon: faMugHot,        tagHint: 'Food' },
  game:     { label: 'Game Time',    icon: faGamepad,       tagHint: 'Game' },
  camp:     { label: 'Campout',      icon: faCampground,    tagHint: 'Other' },
  frog:     { label: 'Frog Mode',    icon: faFrog,          tagHint: 'Other' },
  hiking:   { label: 'Hiking Trek',  icon: faPersonHiking,  tagHint: 'Other' },
  paw:      { label: 'Pet Lovers',   icon: faPaw,           tagHint: 'Other' },
  cat:      { label: 'Cat Cult',     icon: faCat,           tagHint: 'Other' },
  bird:     { label: 'Free Bird',    icon: faCrow,          tagHint: 'Other' },
  gift:     { label: 'Gift Vibes',   icon: faGift,          tagHint: 'Other' },
  sun:      { label: 'Sunny Day',    icon: faSun,           tagHint: 'Other' },
  code:     { label: 'Dev Mode',     icon: faCode,          tagHint: 'Tech' },
  fire:     { label: 'On Fire',      icon: faFire,          tagHint: 'Other' },
};

export function getIconPattern(raw?: string | null): IconPatternId | null {
  if (!raw) return null;
  const lower = raw.toLowerCase().trim() as IconPatternId;
  return (ICON_PATTERN_IDS as readonly string[]).includes(lower) ? lower : null;
}
